/**
 * The purpose of this class is to display visual information and pass values to the other classes that compute information.
 */
package FinalProject;

import Entities.WebObject;
import Threading.WebThread;
import java.awt.Desktop;
import java.net.URI;
import java.net.URISyntaxException;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import static javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER;
import static javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_AS_NEEDED;
import static javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_NEVER;
import javax.swing.UIManager;

/**
 *
 * @author alexangee, @andresochoa, @alexandermohamed
 */
public class ComputerGUI extends javax.swing.JFrame {

    // Variables needed to compute informaiton.
    static ArrayList<WebObject> webNodes = new ArrayList<>();
    public static String NewEggUrl = "";
    public static String BestBuyUrl = "";
    public static String EBayUrl = "";
    public static String AmazonUrl = "";

    /**
     * Creates new form ComputerGUI
     */
    public ComputerGUI() {
        initComponents();

        WebSitePanel.setVisible(false);
        ScrollWebPanel.setVerticalScrollBarPolicy(VERTICAL_SCROLLBAR_NEVER);
        sort.setVisible(false);
        sortRelevance.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        SearchPanel = new javax.swing.JPanel();
        searchText = new javax.swing.JTextField();
        searchButton = new javax.swing.JButton();
        searchItem = new javax.swing.JLabel();
        sort = new javax.swing.JComboBox<>();
        sortRelevance = new javax.swing.JLabel();
        ScrollWebPanel = new javax.swing.JScrollPane();
        WebSitePanel = new javax.swing.JPanel();
        NewEggPanel = new javax.swing.JPanel();
        NewEggItemName = new javax.swing.JLabel();
        NewEggItemImage = new javax.swing.JLabel();
        NewEggItemDescription = new javax.swing.JTextArea();
        NewEggButton = new javax.swing.JButton();
        NewEggItemPrice = new javax.swing.JLabel();
        NewEggTime = new javax.swing.JLabel();
        NewEggSearchTime = new javax.swing.JLabel();
        AmazonPanel = new javax.swing.JPanel();
        AmazonItemDescription = new javax.swing.JTextArea();
        AmazonItemName = new javax.swing.JLabel();
        AmazonItemButton = new javax.swing.JButton();
        AmazonItemImage = new javax.swing.JLabel();
        AmazonItemPrice = new javax.swing.JLabel();
        AmazonTime = new javax.swing.JLabel();
        AmazonSearchTime = new javax.swing.JLabel();
        BestBuyPanel = new javax.swing.JPanel();
        BestBuyItemDescription = new javax.swing.JTextArea();
        BestBuyItemName = new javax.swing.JLabel();
        BestBuyItemButton = new javax.swing.JButton();
        BestBuyItemImage = new javax.swing.JLabel();
        BestBuyItemPrice = new javax.swing.JLabel();
        BestBuyTime = new javax.swing.JLabel();
        BestBuySearchTime = new javax.swing.JLabel();
        EBayPanel = new javax.swing.JPanel();
        EBayItemDescription = new javax.swing.JTextArea();
        EBayItemName = new javax.swing.JLabel();
        EBayItemButton = new javax.swing.JButton();
        EBayItemImage = new javax.swing.JLabel();
        EBayItemPrice = new javax.swing.JLabel();
        EBayTime = new javax.swing.JLabel();
        EBaySearchTime = new javax.swing.JLabel();
        MenuBar = new javax.swing.JMenuBar();
        FileMenu = new javax.swing.JMenu();
        MenuNew = new javax.swing.JMenuItem();
        MenuSave = new javax.swing.JMenuItem();
        MenuOpen = new javax.swing.JMenuItem();
        MenuExport = new javax.swing.JMenu();
        MenuTxt = new javax.swing.JMenuItem();
        MenuDocx = new javax.swing.JMenuItem();
        EditMenu = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));
        setResizable(false);

        SearchPanel.setBackground(new java.awt.Color(255, 255, 255));

        searchButton.setText("Search");
        searchButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemButtonActionPerformed(evt);
            }
        });

        searchItem.setText("Search for Item: ");

        sort.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Price Highest", "Price Lowest" }));
        sort.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sortActionPerformed(evt);
            }
        });

        sortRelevance.setText("Sort:");

        javax.swing.GroupLayout SearchPanelLayout = new javax.swing.GroupLayout(SearchPanel);
        SearchPanel.setLayout(SearchPanelLayout);
        SearchPanelLayout.setHorizontalGroup(
            SearchPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(SearchPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(SearchPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, SearchPanelLayout.createSequentialGroup()
                        .addGap(0, 562, Short.MAX_VALUE)
                        .addComponent(sortRelevance)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(sort, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(searchButton))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, SearchPanelLayout.createSequentialGroup()
                        .addComponent(searchItem)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(searchText)))
                .addContainerGap())
        );
        SearchPanelLayout.setVerticalGroup(
            SearchPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(SearchPanelLayout.createSequentialGroup()
                .addContainerGap(34, Short.MAX_VALUE)
                .addGroup(SearchPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(searchText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(searchItem))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(SearchPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(searchButton)
                    .addComponent(sort, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(sortRelevance)))
        );

        ScrollWebPanel.setHorizontalScrollBarPolicy(HORIZONTAL_SCROLLBAR_NEVER);

        WebSitePanel.setBackground(new java.awt.Color(255, 255, 255));

        NewEggPanel.setBackground(new java.awt.Color(255, 255, 255));

        NewEggItemName.setText("Item Name");

        NewEggItemDescription.setEditable(false);
        NewEggItemDescription.setColumns(20);
        NewEggItemDescription.setRows(5);

        NewEggButton.setText("Go To Item");
        NewEggButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NewEggButtonActionPerformed(evt);
            }
        });

        NewEggItemPrice.setText("Item Price");

        NewEggTime.setText("Time for search: ");

        NewEggSearchTime.setText("Time in milliseconds");

        javax.swing.GroupLayout NewEggPanelLayout = new javax.swing.GroupLayout(NewEggPanel);
        NewEggPanel.setLayout(NewEggPanelLayout);
        NewEggPanelLayout.setHorizontalGroup(
            NewEggPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, NewEggPanelLayout.createSequentialGroup()
                .addComponent(NewEggItemImage, javax.swing.GroupLayout.PREFERRED_SIZE, 233, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 187, Short.MAX_VALUE)
                .addGroup(NewEggPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, NewEggPanelLayout.createSequentialGroup()
                        .addComponent(NewEggItemName, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(35, 35, 35)
                        .addComponent(NewEggItemPrice, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, NewEggPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, NewEggPanelLayout.createSequentialGroup()
                            .addComponent(NewEggTime)
                            .addGap(18, 18, 18)
                            .addComponent(NewEggSearchTime)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(NewEggButton))
                        .addComponent(NewEggItemDescription, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 384, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(21, 21, 21))
        );
        NewEggPanelLayout.setVerticalGroup(
            NewEggPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(NewEggPanelLayout.createSequentialGroup()
                .addContainerGap(27, Short.MAX_VALUE)
                .addGroup(NewEggPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(NewEggItemName)
                    .addComponent(NewEggItemPrice))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(NewEggItemDescription, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10)
                .addGroup(NewEggPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(NewEggButton)
                    .addComponent(NewEggTime)
                    .addComponent(NewEggSearchTime))
                .addContainerGap())
            .addComponent(NewEggItemImage, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        AmazonPanel.setBackground(new java.awt.Color(255, 255, 255));

        AmazonItemDescription.setEditable(false);
        AmazonItemDescription.setColumns(20);
        AmazonItemDescription.setRows(5);

        AmazonItemName.setText("Item Name");

        AmazonItemButton.setText("Go To Item");
        AmazonItemButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AmazonItemButtonActionPerformed(evt);
            }
        });

        AmazonItemPrice.setText("Item Price");

        AmazonTime.setText("Time for search: ");

        AmazonSearchTime.setText("Time in milliseconds");

        javax.swing.GroupLayout AmazonPanelLayout = new javax.swing.GroupLayout(AmazonPanel);
        AmazonPanel.setLayout(AmazonPanelLayout);
        AmazonPanelLayout.setHorizontalGroup(
            AmazonPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(AmazonPanelLayout.createSequentialGroup()
                .addComponent(AmazonItemImage, javax.swing.GroupLayout.PREFERRED_SIZE, 233, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 186, Short.MAX_VALUE)
                .addGroup(AmazonPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(AmazonPanelLayout.createSequentialGroup()
                        .addComponent(AmazonItemName, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(35, 35, 35)
                        .addComponent(AmazonItemPrice, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(AmazonPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(AmazonItemDescription, javax.swing.GroupLayout.PREFERRED_SIZE, 385, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(AmazonPanelLayout.createSequentialGroup()
                            .addComponent(AmazonTime)
                            .addGap(18, 18, 18)
                            .addComponent(AmazonSearchTime)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(AmazonItemButton))))
                .addGap(22, 22, 22))
        );
        AmazonPanelLayout.setVerticalGroup(
            AmazonPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, AmazonPanelLayout.createSequentialGroup()
                .addContainerGap(21, Short.MAX_VALUE)
                .addGroup(AmazonPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(AmazonItemName)
                    .addComponent(AmazonItemPrice))
                .addGap(18, 18, 18)
                .addComponent(AmazonItemDescription, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(AmazonPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(AmazonItemButton)
                    .addGroup(AmazonPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(AmazonTime)
                        .addComponent(AmazonSearchTime)))
                .addGap(4, 4, 4))
            .addComponent(AmazonItemImage, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        BestBuyPanel.setBackground(new java.awt.Color(255, 255, 255));

        BestBuyItemDescription.setEditable(false);
        BestBuyItemDescription.setColumns(20);
        BestBuyItemDescription.setRows(5);

        BestBuyItemName.setText("Item Name");

        BestBuyItemButton.setText("Go To Item");
        BestBuyItemButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BestBuyItemButtonActionPerformed(evt);
            }
        });

        BestBuyItemPrice.setText("Item Price");

        BestBuyTime.setText("Time for search: ");

        BestBuySearchTime.setText("Time in milliseconds");

        javax.swing.GroupLayout BestBuyPanelLayout = new javax.swing.GroupLayout(BestBuyPanel);
        BestBuyPanel.setLayout(BestBuyPanelLayout);
        BestBuyPanelLayout.setHorizontalGroup(
            BestBuyPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(BestBuyPanelLayout.createSequentialGroup()
                .addComponent(BestBuyItemImage, javax.swing.GroupLayout.PREFERRED_SIZE, 233, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 186, Short.MAX_VALUE)
                .addGroup(BestBuyPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(BestBuyPanelLayout.createSequentialGroup()
                        .addComponent(BestBuyItemName, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(35, 35, 35)
                        .addComponent(BestBuyItemPrice, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(BestBuyPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(BestBuyItemDescription, javax.swing.GroupLayout.PREFERRED_SIZE, 385, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(BestBuyPanelLayout.createSequentialGroup()
                            .addGap(6, 6, 6)
                            .addComponent(BestBuyTime)
                            .addGap(18, 18, 18)
                            .addComponent(BestBuySearchTime)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(BestBuyItemButton))))
                .addGap(22, 22, 22))
        );
        BestBuyPanelLayout.setVerticalGroup(
            BestBuyPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, BestBuyPanelLayout.createSequentialGroup()
                .addContainerGap(21, Short.MAX_VALUE)
                .addGroup(BestBuyPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BestBuyItemName)
                    .addComponent(BestBuyItemPrice))
                .addGap(18, 18, 18)
                .addComponent(BestBuyItemDescription, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(BestBuyPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(BestBuyItemButton)
                    .addGroup(BestBuyPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(BestBuyTime)
                        .addComponent(BestBuySearchTime)))
                .addGap(4, 4, 4))
            .addComponent(BestBuyItemImage, javax.swing.GroupLayout.PREFERRED_SIZE, 233, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        EBayPanel.setBackground(new java.awt.Color(255, 255, 255));

        EBayItemDescription.setEditable(false);
        EBayItemDescription.setColumns(20);
        EBayItemDescription.setRows(5);

        EBayItemName.setText("Item Name");

        EBayItemButton.setText("Go To Item");
        EBayItemButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EBayItemButtonActionPerformed(evt);
            }
        });

        EBayItemPrice.setText("Item Price");

        EBayTime.setText("Time for search: ");

        EBaySearchTime.setText("Time in milliseconds");

        javax.swing.GroupLayout EBayPanelLayout = new javax.swing.GroupLayout(EBayPanel);
        EBayPanel.setLayout(EBayPanelLayout);
        EBayPanelLayout.setHorizontalGroup(
            EBayPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(EBayPanelLayout.createSequentialGroup()
                .addComponent(EBayItemImage, javax.swing.GroupLayout.PREFERRED_SIZE, 233, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 186, Short.MAX_VALUE)
                .addGroup(EBayPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(EBayPanelLayout.createSequentialGroup()
                        .addComponent(EBayItemName, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(35, 35, 35)
                        .addComponent(EBayItemPrice, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(EBayPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(EBayItemDescription, javax.swing.GroupLayout.PREFERRED_SIZE, 385, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(EBayPanelLayout.createSequentialGroup()
                            .addComponent(EBayTime)
                            .addGap(18, 18, 18)
                            .addComponent(EBaySearchTime)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(EBayItemButton))))
                .addGap(22, 22, 22))
        );
        EBayPanelLayout.setVerticalGroup(
            EBayPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, EBayPanelLayout.createSequentialGroup()
                .addContainerGap(21, Short.MAX_VALUE)
                .addGroup(EBayPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(EBayItemName)
                    .addComponent(EBayItemPrice))
                .addGap(18, 18, 18)
                .addComponent(EBayItemDescription, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(EBayPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(EBayItemButton)
                    .addGroup(EBayPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(EBayTime)
                        .addComponent(EBaySearchTime)))
                .addGap(4, 4, 4))
            .addComponent(EBayItemImage, javax.swing.GroupLayout.PREFERRED_SIZE, 233, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        javax.swing.GroupLayout WebSitePanelLayout = new javax.swing.GroupLayout(WebSitePanel);
        WebSitePanel.setLayout(WebSitePanelLayout);
        WebSitePanelLayout.setHorizontalGroup(
            WebSitePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(NewEggPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(AmazonPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(BestBuyPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(EBayPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        WebSitePanelLayout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {AmazonPanel, BestBuyPanel, EBayPanel, NewEggPanel});

        WebSitePanelLayout.setVerticalGroup(
            WebSitePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, WebSitePanelLayout.createSequentialGroup()
                .addComponent(NewEggPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(AmazonPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(BestBuyPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(EBayPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        WebSitePanelLayout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {AmazonPanel, BestBuyPanel, EBayPanel, NewEggPanel});

        ScrollWebPanel.setViewportView(WebSitePanel);

        FileMenu.setText("File");

        MenuNew.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_N, java.awt.event.InputEvent.CTRL_MASK));
        MenuNew.setText("New...");
        MenuNew.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuNewActionPerformed(evt);
            }
        });
        FileMenu.add(MenuNew);

        MenuSave.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_S, java.awt.event.InputEvent.CTRL_MASK));
        MenuSave.setText("Save");
        MenuSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuSaveActionPerformed(evt);
            }
        });
        FileMenu.add(MenuSave);

        MenuOpen.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_O, java.awt.event.InputEvent.CTRL_MASK));
        MenuOpen.setText("Open");
        FileMenu.add(MenuOpen);

        MenuExport.setText("Export...");

        MenuTxt.setText("As txt");
        MenuExport.add(MenuTxt);

        MenuDocx.setText("As docx");
        MenuExport.add(MenuDocx);

        FileMenu.add(MenuExport);

        MenuBar.add(FileMenu);

        EditMenu.setText("Edit");
        MenuBar.add(EditMenu);

        setJMenuBar(MenuBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(ScrollWebPanel)
                    .addComponent(SearchPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(SearchPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ScrollWebPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 511, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /*
     * This method creates a thread for each retailer and passes information accordingly.
     */
    private void itemButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemButtonActionPerformed

        // Initializes each thread
        WebThread NewEgg = new WebThread(searchText.getText(), 0);
        WebThread BestBuy = new WebThread(searchText.getText(), 1);
        WebThread EBay = new WebThread(searchText.getText(), 2);
        WebThread Amazon = new WebThread(searchText.getText(), 3);

        // Starts the thread
        NewEgg.start();
        BestBuy.start();
        EBay.start();
        Amazon.start();

        WebSitePanel.setVisible(true);
        ScrollWebPanel.setVerticalScrollBarPolicy(VERTICAL_SCROLLBAR_AS_NEEDED);
    }//GEN-LAST:event_itemButtonActionPerformed

    /**
     *
     * This method allows the user to access the item they searched for on
     * NewEgg. Uses the default/preferred user web browser.
     */
    private void NewEggButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NewEggButtonActionPerformed

        URI uri = null;
        try {
            uri = new URI(NewEggUrl);
        } catch (URISyntaxException ex) {
            JOptionPane.showMessageDialog(rootPane, ex);
        }

        openWebpage(uri);
    }//GEN-LAST:event_NewEggButtonActionPerformed

    /**
     *
     * This method allows the user to access the item they searched for on
     * Amazon. Uses the default/preferred user web browser.
     */
    private void AmazonItemButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AmazonItemButtonActionPerformed

        URI uri = null;
        try {
            uri = new URI(AmazonUrl);
        } catch (URISyntaxException ex) {
            JOptionPane.showMessageDialog(rootPane, ex);
        }

        openWebpage(uri);
    }//GEN-LAST:event_AmazonItemButtonActionPerformed

    /**
     *
     * This method allows the user to access the item they searched for on Best
     * Buy. Uses the default/preferred user web browser.
     */
    private void BestBuyItemButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BestBuyItemButtonActionPerformed

        URI uri = null;
        try {
            uri = new URI(BestBuyUrl);
        } catch (URISyntaxException ex) {
            JOptionPane.showMessageDialog(rootPane, ex);
        }

        openWebpage(uri);
    }//GEN-LAST:event_BestBuyItemButtonActionPerformed

    /**
     *
     * This method allows the user to access the item they searched for on
     * NewEgg. Uses the default/preferred user web browser.
     */
    private void EBayItemButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EBayItemButtonActionPerformed

        URI uri = null;
        try {
            uri = new URI(EBayUrl);
        } catch (URISyntaxException ex) {
            JOptionPane.showMessageDialog(rootPane, ex);
        }

        openWebpage(uri);
    }//GEN-LAST:event_EBayItemButtonActionPerformed

    /**
     *
     * Not yet functional sort method.
     */
    private void sortActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sortActionPerformed
        // TODO add your handling code here:
        sortByRelevancy(sort.getSelectedItem().toString());
    }//GEN-LAST:event_sortActionPerformed

    private void MenuNewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuNewActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_MenuNewActionPerformed

    private void MenuSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuSaveActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_MenuSaveActionPerformed

    /**
     *
     * Multi-Threaded merge sort by price highest/lowest
     */
    public void sortByRelevancy(String sort) {

        switch (sort) {
            // Price Highest
            case "Price Highest": {

                break;
            }
            // Price Lowest
            case "Price Lowest": {

                break;
            }
            default: {
                break;
            }
        }

    }

    /**
     *
     * Allows the user to opens a specified url in their default browser.
     */
    public void openWebpage(URI uri) {
        Desktop desktop = Desktop.isDesktopSupported() ? Desktop.getDesktop() : null;
        if (desktop != null && desktop.isSupported(Desktop.Action.BROWSE)) {
            try {
                desktop.browse(uri);
            } catch (Exception e) {
                JOptionPane.showMessageDialog(rootPane, e.getMessage());
            }
        }
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ComputerGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ComputerGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ComputerGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ComputerGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new ComputerGUI().setVisible(true);
            try {
                UIManager.setLookAndFeel(UIManager.getSystemLookAndFeelClassName());
            } catch (Exception e) {
                System.out.println(e);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public static javax.swing.JButton AmazonItemButton;
    public static javax.swing.JTextArea AmazonItemDescription;
    public static javax.swing.JLabel AmazonItemImage;
    public static javax.swing.JLabel AmazonItemName;
    public static javax.swing.JLabel AmazonItemPrice;
    public static javax.swing.JPanel AmazonPanel;
    public static javax.swing.JLabel AmazonSearchTime;
    public static javax.swing.JLabel AmazonTime;
    public static javax.swing.JButton BestBuyItemButton;
    public static javax.swing.JTextArea BestBuyItemDescription;
    public static javax.swing.JLabel BestBuyItemImage;
    public static javax.swing.JLabel BestBuyItemName;
    public static javax.swing.JLabel BestBuyItemPrice;
    public static javax.swing.JPanel BestBuyPanel;
    public static javax.swing.JLabel BestBuySearchTime;
    public static javax.swing.JLabel BestBuyTime;
    public static javax.swing.JButton EBayItemButton;
    public static javax.swing.JTextArea EBayItemDescription;
    public static javax.swing.JLabel EBayItemImage;
    public static javax.swing.JLabel EBayItemName;
    public static javax.swing.JLabel EBayItemPrice;
    public static javax.swing.JPanel EBayPanel;
    public static javax.swing.JLabel EBaySearchTime;
    public static javax.swing.JLabel EBayTime;
    private javax.swing.JMenu EditMenu;
    private javax.swing.JMenu FileMenu;
    private javax.swing.JMenuBar MenuBar;
    private javax.swing.JMenuItem MenuDocx;
    private javax.swing.JMenu MenuExport;
    private javax.swing.JMenuItem MenuNew;
    private javax.swing.JMenuItem MenuOpen;
    private javax.swing.JMenuItem MenuSave;
    private javax.swing.JMenuItem MenuTxt;
    public static javax.swing.JButton NewEggButton;
    public static javax.swing.JTextArea NewEggItemDescription;
    public static javax.swing.JLabel NewEggItemImage;
    public static javax.swing.JLabel NewEggItemName;
    public static javax.swing.JLabel NewEggItemPrice;
    public static javax.swing.JPanel NewEggPanel;
    public static javax.swing.JLabel NewEggSearchTime;
    public static javax.swing.JLabel NewEggTime;
    public static javax.swing.JScrollPane ScrollWebPanel;
    public static javax.swing.JPanel SearchPanel;
    public static javax.swing.JPanel WebSitePanel;
    public static javax.swing.JButton searchButton;
    public static javax.swing.JLabel searchItem;
    public static javax.swing.JTextField searchText;
    public static javax.swing.JComboBox<String> sort;
    public static javax.swing.JLabel sortRelevance;
    // End of variables declaration//GEN-END:variables

}
